baseurl = "/"
title = "Conference name"
canonifyurls = true
theme = "hugo-conference"
GoogleAnalytics = ""

[params]
Name = "Conference name"
Description = "Conference description"
Date = "November 15"
Price = "Only $100"
Venue = "Coco Bongo"
Address = "Boulevard Kukulcan, 30"
City = "Cancún"
State = "Quintana"
Images = [
  "/img/badge.jpg"
]
GoogleMapsKey = "my-secret-maps-key"
Sections = [
  "about",
  "location",
  "speakers",
  "schedule",
  "sponsors",
  "partners"
]

  [params.Titles]
  about = "About"
  location = "Location"
  speakers = "Speakers"
  schedule = "Schedule"
  sponsors = "Sponsors"
  partners = "Partners"
  contact = "Contact"

  [params.CallToAction]
  text = "Register now!"
  link = "http://register.example.com"

  [params.ForkButton]
  repository = "https://github.com/jweslley/hugo-conference/"

  [[params.Sponsors]]
  name = "Hugo"
  logo = "/img/hugo.png"
  url = "http://gohugo.io"

  [[params.Partners]]
  name = "Hugo"
  logo = "/img/hugo.jpg"
  url = "https://gohugo.io"

  [[params.Partners]]
  name = "BrazilJS"
  logo = "/img/partner.png"
  url = "http://braziljs.org"

  [[params.Schedule]]
  name = "Check-in / Breakfast"
  time = "9h00"

  [[params.Schedule]]
  name = "Linus Torvalds"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Linux Foundation"

    [params.Schedule.link]
    href = "http://twitter.com/linus"
    text = "@linus"

    [params.Schedule.presentation]
    title = "Digging into a Linux Kernel"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "10h00"

  [[params.Schedule]]
  name = "Bill Gates"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Microsoft"

    [params.Schedule.link]
    href = "http://github.com/billy95"
    text = "@billy95"

    [params.Schedule.presentation]
    title = "Introducing Windows 12"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "11h00"

  [[params.Schedule]]
  name = "Lunch"
  time = "12h00"

  [[params.Schedule]]
  name = "Chuck Norris"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Delta Command"

    [params.Schedule.link]
    href = "http://twitter.com/littlechuck"
    text = "@littlechuck"

    [params.Schedule.presentation]
    title = "How to kill a elephant with one finger"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "13h00"

  [[params.Schedule]]
  name = "Steve Jobs"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Apple, Inc."

    [params.Schedule.link]
    href = "http://github.com/stevie"
    text = "@stevie"

    [params.Schedule.presentation]
    title = "Presenting iPad"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "14h00"

  [[params.Schedule]]
  name = "Coffee-break"
  time = "15h00"

  [[params.Schedule]]
  name = "Mark Zuckerberg"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Facebook"

    [params.Schedule.link]
    href = "http://twitter.com/zuck"
    text = "@zuck"

    [params.Schedule.presentation]
    title = "Revealing Facebook Secrets"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "16h00"

  [[params.Schedule]]
  name = "Steve Wozniak"
  photo = "/img/speaker.jpg"
  bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  company = "Apple, Inc."

    [params.Schedule.link]
    href = "http://twitter.com/woz"
    text = "@woz"

    [params.Schedule.presentation]
    title = "Why do I prefer Android over iPhone"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    time = "17h00"